# Generated by Django 4.0 on 2021-12-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('compensation', models.DecimalField(decimal_places=10, max_digits=20)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('ZAR', 'ZAR'), ('BTC', 'BTC'), ('ETH', 'ETH')], default='USD', max_length=255)),
                ('interval', models.CharField(blank=True, choices=[('hr', 'hr'), ('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='day', max_length=255)),
                ('industry', models.CharField(blank=True, choices=[('Accounting', 'Accounting'), ('Advertising', 'Advertising'), ('Agriculture', 'Agriculture'), ('Banking & Finance', 'Banking & Finance'), ('Construction', 'Construction'), ('None', 'None'), ('Computer Programming', 'Computer Programming')], default='None', max_length=255)),
                ('experience', models.CharField(blank=True, choices=[('Student', 'Student'), ('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior'), ('Expert', 'Expert')], default='Junior', max_length=255)),
                ('tech', models.TextField(blank=True, max_length=995)),
                ('environment', models.CharField(blank=True, choices=[('Not Specified', 'Not Specified'), ('Remote', 'Remote'), ('Office', 'Office')], default='Not Specified', max_length=255)),
                ('mode', models.CharField(blank=True, choices=[('Contract', 'Contract'), ('Permanent', 'Permanent'), ('Internship', 'Internship')], default='Contract', max_length=255)),
                ('benefits', models.TextField(blank=True, max_length=995)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-created'],
            },
        ),
    ]
