# Generated by Django 4.0 on 2021-12-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_compensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='compensation',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
